services:
  db:
    image: postgres:latest
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
    # expose:
    #   - 5432
    ports:
      - 5432:5432
    networks:
      - be-network
    restart: always
    hostname: postgres
    command: -p 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  # web:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./:/app
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  #   depends_on:
  #     - be-network
  #   networks:
  #     - be-network
    backend:
      image: huyqcl377/sample_prj:latest
      volumes: 
        - ./:/app
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      depends_on:
        - be-network
      networks:
        - be-network


      

networks:
  be-network:
    # driver: bridge